######################################################
## File upload handlers
## 
## Take TSV generated by WOS and format into standard
## form. 
##
## Allow user to upload multiple files at once, or
## pending files one by one.
######################################################

# Dependency
library(shiny)
source('./src/modules/upload_files/data.R')

#' upload file server component (requires, upload_file_server)
#' 
#' @param id namespace (can be any string, but needs to be same as ui)
#' @param label any label that makes sense
#' @examples
#' upload_file_ui("upload")
#' See "Shiny Module" for more details
mod_upload_file_ui<- function(id, label = "Input text: ") {
  ns <- NS(id)
  tagList(
    checkboxInput(inputId = ns("clear_data"), label = "Clear Data", value = T),
    fileInput(inputId = ns('data_file'), 
              label = "Upload Data File (WoS)", 
              multiple = TRUE,
              accept = c("txt/tsv", ".txt", '.csv'))
  )
}

#' upload file server component (requires, upload_file_ui)
#' 
#' @param id namespace (can be any string, but needs to be same as ui)
#' @return data that is loaded (this is reactive component)
#' @examples
#' uploade_file_server("upload")
#' See "Shiny Module" for more details
mod_upload_file_server <- function(id) {
  moduleServer(
    id,
    function(input, output, session) {
      
      rv <- reactiveValues()
      
      # observe changes
      observeEvent(input$data_file, {
        # Create a Progress object
        progress <- shiny::Progress$new()
        # Make sure it closes when we exit this reactive, even if there's an error
        on.exit(progress$close())
        
        progress$set(message = "Loading data...", value = 0)
        
        cat(file = stderr(), "module_upload_files.R: loading data", input$data_file$datapath, "\n")
        
        if(input$clear_data == T)
          clear_data = T
        else
          clear_data = F
        
        # referring to function to service data_processing.R
        # concatenate if rv$data exists
        if(!clear_data && !is.null(rv$data)){
          rv$data <- read_data_file(input$data_file$datapath, df = rv$data) %>% drop_na(year)
        } else {
          rv$data <- read_data_file(input$data_file$datapath) %>% drop_na(year)
        }
        
        cat(file = stderr(), "module_upload_files.R: loaded", nrow(rv$data), "rows", "\n")

      })
      
      data <- reactive({
        rv$data
      })
      
     return(data) 
    }
  )
}